name: "Nibe MQTT"
description: "Nibe MQTT Add-On"
version: "0.1.0"
slug: "nibe_mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
# host network provides original source UDP address
host_network: true
ports:
  9999/udp: 9999
services:
  - mqtt:need
map:
  - config:rw

